// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'flashcard.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 2558140686066709435),
      name: 'FlashCard',
      lastPropertyId: const IdUid(3, 1461881085228617747),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 7696430882656486102),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 5472669533774908733),
            name: 'word',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 1461881085228617747),
            name: 'star',
            type: 1,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 2558140686066709435),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    FlashCard: EntityDefinition<FlashCard>(
        model: _entities[0],
        toOneRelations: (FlashCard object) => [],
        toManyRelations: (FlashCard object) => {},
        getId: (FlashCard object) => object.id,
        setId: (FlashCard object, int id) {
          object.id = id;
        },
        objectToFB: (FlashCard object, fb.Builder fbb) {
          final wordOffset = fbb.writeString(object.word);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, wordOffset);
          fbb.addBool(2, object.star);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = FlashCard(
              word: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              star:
                  const fb.BoolReader().vTableGet(buffer, rootOffset, 8, false))
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [FlashCard] entity fields to define ObjectBox queries.
class FlashCard_ {
  /// see [FlashCard.id]
  static final id = QueryIntegerProperty<FlashCard>(_entities[0].properties[0]);

  /// see [FlashCard.word]
  static final word =
      QueryStringProperty<FlashCard>(_entities[0].properties[1]);

  /// see [FlashCard.star]
  static final star =
      QueryBooleanProperty<FlashCard>(_entities[0].properties[2]);
}
